# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-08 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='account',
            new_name='account_id',
        ),
    ]
