# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190307_0925'),
        ('account', '0002_auto_20190307_0928'),
    ]

    operations = [
    ]
