# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('password', models.CharField(max_length=45, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
