# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Paused", "Paused"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=255,
                    ),
                ),
                ("insert_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "Status"},
        )
    ]
