# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190301_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='students',
        ),
    ]
