# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190301_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
