# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0006_auto_20190308_1400")]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lock_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="status",
            name="name",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Paused", "Paused"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Active",
                max_length=255,
            ),
        ),
    ]
