# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190301_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscription_date',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='update_date',
        ),
    ]
