# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20190301_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], default='ACTIVE', max_length=255),
        ),
    ]
