# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190301_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='subscription_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
